name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Build
        run: cargo build --verbose

      - name: Clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Run test with status codes
        run: cargo run -- 202 404 503
